# image-updater/chai-app/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list the manifest files in this directory
resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml

# (optional) you can put commonLabels or namespace here if you want
# commonLabels:
#   app: chai-app
